# Generated by Django 5.2.5 on 2025-09-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_shippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="full_name",
        ),
    ]
