# Generated by Django 5.2.5 on 2025-09-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_shippingaddress_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
