version: '3.8'

services:
  backend:
    build: .
    env_file:
      - ./.env
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env

volumes:
  postgres_data: