# Generated by Django 5.2.5 on 2025-09-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Debit Card"),
                    ("wallet", "Digital Wallet"),
                    ("cod", "Cash on Delivery"),
                ],
                db_index=True,
                default="card",
                max_length=20,
            ),
        ),
    ]
