# Generated by Django 5.2.5 on 2025-09-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="updated_at",
        ),
    ]
