# Generated by Django 5.2.5 on 2025-09-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
    ]
