# Generated by Django 5.2.5 on 2025-09-03 08:58
# orders/migrations/0006_shipping_address_fk_safely.py
from django.db import migrations, models
import django.db.models.deletion


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0005_alter_order_options_alter_orderitem_options",
        ),  # ← ПОМЕНЯЙ на фактическую предыдущую миграцию orders
        ("users", "0003_shippingaddress"),  # твоя миграция с адресами уже применена
    ]

    operations = [
        # 1) Добавляем новое FK-поле с другим именем, чтобы не конфликтовало со старым TEXT полем
        migrations.AddField(
            model_name="order",
            name="shipping_address_fk",
            field=models.ForeignKey(
                to="users.shippingaddress",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_fk",
                null=True,
                blank=True,
            ),
        ),
        # 2) (Опционально) Если хочешь попробовать сопоставить строки — тут можно вставить RunPython,
        # но безопаснее просто оставить None:
        migrations.RunPython(noop, reverse_code=noop),
        # 3) Добавляем снимочные поля доставки (если их ещё нет; если уже есть — убери соответствующие AddField)
        migrations.AddField(
            model_name="order",
            name="ship_recipient_name",
            field=models.CharField(max_length=200, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="ship_phone",
            field=models.CharField(max_length=30, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="ship_country",
            field=models.CharField(max_length=100, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="ship_city",
            field=models.CharField(max_length=100, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="ship_postcode",
            field=models.CharField(max_length=20, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="ship_address_line1",
            field=models.CharField(max_length=255, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="ship_address_line2",
            field=models.CharField(max_length=255, blank=True, default=""),
        ),
        # 4) Удаляем старое текстовое поле shipping_address (SQLite пересоздаст таблицу — теперь безопасно)
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        # 5) Переименовываем новое FK-поле на итоговое имя 'shipping_address'
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address_fk",
            new_name="shipping_address",
        ),
    ]
