# Generated by Django 5.2.5 on 2025-09-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_options_alter_orderitem_options_and_more"),
        ("users", "0004_remove_shippingaddress_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ship_address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="ship_recipient_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="users.shippingaddress",
            ),
        ),
    ]
