# Generated by Django 5.2.5 on 2025-08-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(blank=True, default="USD", max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_measure",
            field=models.TextField(blank=True, default="kg", max_length=5, null=True),
        ),
    ]
