# Generated by Django 5.2.5 on 2025-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_currency_product_unit_measure"),
        ("products", "0002_productreview"),
    ]

    operations = []
