# Generated by Django 5.2.5 on 2025-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_merge_20250821_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="title",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_measure",
            field=models.TextField(default="kg", max_length=5),
        ),
    ]
