# Generated by Django 5.2.5 on 2025-08-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productreview_title_alter_product_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTechSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_spec", models.JSONField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_specs",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
