# Generated by Django 5.2.5 on 2025-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_producttechspec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttechspec",
            name="tech_spec",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
