# Generated by Django 5.2.5 on 2025-08-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_producttechspec_tech_spec"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttechspec",
            options={
                "verbose_name": "Product Tech Spec",
                "verbose_name_plural": "Product Tech Specs",
            },
        ),
    ]
