# Generated by Django 5.2.5 on 2025-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_producttechspec_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="product_images/no-image.png",
                null=True,
                upload_to="product_images/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_measure",
            field=models.TextField(default="kg", max_length=20),
        ),
    ]
